# Dockerfile
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy project
COPY . .

# Expose the port Django will run on
EXPOSE 8000

# Run the development server
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]