# Generated by Django 4.2.7 on 2024-06-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dairy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gluten',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='lowsugar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='meat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
