# Generated by Django 4.2.7 on 2024-06-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_item_dairy_item_gluten_item_image_item_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
